name: Releases

on: 
  push:
    branches-ignore:
    - '**'
    tags-ignore:
    - '*rc'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}